### ISSUE TITLE
Instant.Now - serialises to ticks but should be mSec?

### ISSUE THREAD

**Issue by johnsondaj** [FirelyTeam/fhir-net-api#1399] opened 2020-06-15 17:14 UTC
I have this code:
                Meta = new Meta()
                {
                    VersionId = "1",
                    LastUpdatedElement = Instant.Now()
                },

When I serialize it to JSON the output looks like this:
    <meta>
        <versionId value="1" />
        <lastUpdated value="2020-06-15T17:58:13.0134712+01:00" />
    </meta>

So I was expecting milliseconds but what I am seeing is a 7 digit tick value (each tick being 100nS).

The FHIR standard says
"An instant in time in the format YYYY-MM-DDThh:mm:ss.sss+zz:zz (e.g. 2015-02-07T13:28:17.239+02:00 or 2017-01-01T00:00:00Z)."

So that seems to me to say that only milliseconds are supported, is this correct? and hence is this a bug?

**Comment by johnsondaj** [comment] 2020-06-15 18:24
Sorry, this is what the output looks like currently

<meta>
        <versionId value="1" />
        <lastUpdated value="2020-06-15T19:23:53.7247525+01:00" />
    </meta>

**Comment by johnsondaj** [comment] 2020-06-15 18:25
<lastUpdated value="2020-06-15T19:23:53.7247525+01:00" />

**Comment by marcovisserFurore** [comment] 2020-06-16 10:50
so correct, right?

**Comment by johnsondaj** [comment] 2020-06-16 12:26
Sorry, what I was trying to say is that the FHIR standard seems to be saying that only milliseconds (3 digits) are supported - but the library is serializing 7 digit ticks - so instead of .7247525 I was actually expecting to see .725?

In fact I suspect the number of ticks that are generated is variable depending on the actual value - I've see 6 digit ticks generated and if you were un/lucky enough you could see a one digit tick? This just doesn't seem right to me?

**Comment by marcovisserFurore** [comment] 2020-06-16 13:51
When you closely at the spec http://hl7.org/fhir/datatypes.html#instant, you will see that there is also a regex mentioned:

```
([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))
```
And that is what we use in the FHIR API. It means that it can have 'endless' of digits for milliseconds.

I agree that the spec is not consistent about this. I will file a ticket to HL7 to change it.

**Comment by marcovisserFurore** [comment] 2020-06-16 14:05
I also created an unit test to show that the value we produce is valid:

```
        [Fact]
        public void InstanceHasValidValue()
        {
            var patient = new Patient { Meta = new Meta { LastUpdatedElement = Instant.Now() } };
            var xml = patient.ToXml();

            var source = FhirXmlNode.Parse(xml);

            var value = source.Children("meta").Children("lastUpdated").FirstOrDefault();

            Assert.True(Instant.IsValidValue(value?.Text ?? string.Empty));
        }
```

**Comment by marcovisserFurore** [comment] 2020-06-16 14:09
Task:

- [ ] The spec says that the format of instant should have the following format `YYYY-MM-DDThh:mm:ss.sss+zz:zz` (e.g. `2015-02-07T13:28:17.239+02:00`). The regex says that it can multiple digits for milliseconds. Create a HL7 ticket to change this.

**Comment by johnsondaj** [comment] 2020-06-16 14:10
Thanks for the response I'm fairly new to this.

Still not sure about the case where you currently generate less than 7 tick digits though - pretty sure I saw a case with 6 digits where I guess the leading zero was lost - that doesn't seem right, you should always have 7 digits with leading zeroes as needed? Maybe I was imagining it.

**Comment by marcovisserFurore** [comment] 2020-06-16 14:20
Also that is correct: look at this unittest:

```
        [Fact]
        public void InstanceHasValidValue()
        {
            var patient = new Patient { Meta = new Meta { LastUpdated = new DateTimeOffset(2020, 6, 16, 16, 12, 2, 3, TimeSpan.Zero) } };
            var xml = patient.ToXml();

            var source = FhirXmlNode.Parse(xml);

            var value = source.Children("meta").Children("lastUpdated").FirstOrDefault();

            Assert.True(Instant.IsValidValue(value?.Text ?? string.Empty));
        }
```

It will serialize like this:

```
<Patient xmlns="http://hl7.org/fhir"><meta><lastUpdated value="2020-06-16T16:12:02.003+00:00" /></meta></Patient>
```

So only with 3 digits

**Comment by johnsondaj** [comment] 2020-06-16 14:53
The problem I saw was with Instant.Now()

**Comment by marcovisserFurore** [comment] 2020-06-16 20:17
Ok, if you are able to reproduce it, then let us know. We can take a look at it.

**Comment by marcovisserFurore** [comment] 2020-07-01 13:09
The number of digits next to the second, determines the fractional part of second:
- 1 digit means tenth of a second, so `.3` means 3 tenth of second
- 2 digits means hundreds of a second, so `.03' means 3 hundreds of a second
- 3 digits means thousands of a second, so `.003` means 3 thousands of a second
- 4 digits means tenthousands of a second, so `.005` means 5 tenthousands of a second
- etc

See also https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-display-milliseconds-in-date-and-time-values#example

**Comment by marcovisserFurore** [comment] 2020-07-01 13:09
I close this issue, because it is no bug of the api

**Closed by marcovisserFurore** 2020-07-01 13:09 UTC
Labels: awaiting response, support
