### ISSUE TITLE
netstandard1.1 issue from .Net Framework 4.5.2 project DateTime Response.LastModified

### ISSUE THREAD

**Issue by JohnCrichton81** [FirelyTeam/fhir-net-api#1113] opened 2019-09-17 07:30 UTC
Hello,
I am working on a framework 4.5.2 project using as nuget package Hl7.Fhir.Specification.STU3.
I have no problems to send a fhir message and my issue concerns the response to my message and more precisely a property called LastModifed.

I know there was a an issue recently and  a netstandard condition was added : 

```
'#if NETSTANDARD1_1
            if (!String.IsNullOrEmpty(response.Headers[HttpUtil.LASTMODIFIED]))
            {
                DateTimeOffset dateTimeOffset = new DateTimeOffset();
                bool success = DateTimeOffset.TryParse(response.Headers[HttpUtil.LASTMODIFIED], out dateTimeOffset);
                if (!success)
                    throw new FormatException($"Last-Modified header has value '{response.Headers[HttpUtil.LASTMODIFIED]}', which is not recognized as a valid DateTime");
                result.Response.LastModified = dateTimeOffset;
            }
#else
           result.Response.LastModified = response.LastModified;
#endif`
```

Using Framework 4.5.2, I think that I should probably pass on the condition NetStandard1_1 and I am always in the "else" having an exception. Everything works fine when I modify this code to always pass through the netstandard condition (just commenting the condition)

I am not a .Net specialist but is it normal ? And how can I fix this ? I cannot change my framework version (many other projects related)

Thanks by advance.

**Comment by JohnCrichton81** [comment] 2019-09-17 09:50
I added a targetframework on the package reference : 

```
<ItemGroup>
    <PackageReference Include="Hl7.Fhir.Specification.STU3" TargetFramework="netstandard1.1" Version="1.3.0"/>
  </ItemGroup>
```
But I have the same issue.

**Comment by marcovisserFurore** [comment] 2019-09-30 09:55
This is duplicate of #1119

**Comment by ewoutkramer** [comment] 2020-09-10 15:14
I am not so sure it's a duplicate. In #1119, the error was because of Google sending an incorrect header.....

**Comment by ewoutkramer** [comment] 2020-09-10 15:18
It does seem to be a problem with parsing the header indeed.  @JohnCrichton81 - if you were still able to report what's in the header, we can ensure this is probably an incorrectly formatted header - and then the exception would be correct?   If not, I suppose we should close this.

**Comment by ewoutkramer** [comment] 2020-09-17 10:10
We've done further research.  What happens is this:

* An incorrect time header with a timezone (like PST - see #1119 for an example) arrives in the header.
* The NETSTD1.1 version uses DateTimeOffset.TryParse -> this function actually accepts this format.
* The "normal" netstandard uses the LastModified property that is part of the MS standard library (doesn't exist in 1.1). This library (we looked at the source code) actually has internal datetime parsing logic - and detects that the header is illegal.

So, yes, there is difference in behaviour, and in fact the nestd1.1 version is too lenient.  So, if anything, we should make the 1.1 version work like the >1.1 version of netstandard.

**Closed by ewoutkramer** 2020-09-17 10:10 UTC
Labels: bug
