### ISSUE TITLE
Read Observation throwing Error

### ISSUE THREAD

**Issue by tscrip** [FirelyTeam/fhir-net-api#1524] opened 2020-10-29 16:44 UTC
**Describe the bug**
I am fairly new to this project, but I have been able to use it for several things with great success. When I attempt to pull an Observation value via Read, I am getting an error message from the library. I can take this exact same code and dummy up the request via PostMan without any problems.

Here is the error message I am getting: 
```
Must be a FHIR REST url containing the resource type in its path (Parameter 'location')
```

**To Reproduce**
1. Create a simple example like this:
```
var accessToken = "abc123";
var url = "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/STU3";
var client = new FhirClient(url);
client.OnBeforeRequest += (object sender, BeforeRequestEventArgs e) =>
            {
                e.RawRequest.Headers.Add("Authorization", "Bearer " + accessToken);
            };
var result = client.Read<Observation>("Observation?patient=eAB3mDIBBcyUKviyzrxsnAw3&code=4548-4");
// ERROR is thrown HERE: Must be a FHIR REST url containing the resource type in its path (Parameter 'location')
```

**Expected behavior**
I have been able to use this exact same code with the following Resource Types: Referral, Encounter, Location, Organization, and Patient. This works perfectly for everything except Observations.

Additionally, I can dummy up a Postman request like this:
```
[GET] https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/STU3/Observation?patient=eAB3mDIBBcyUKviyzrxsnAw3&code=4548-4
```
And it return the correct value every time.

**Version used:**
 - FHIR Version: STU3

**Comment by marcovisserFurore** [comment] 2020-10-29 17:54
Hi @tscrip ,

You are trying to search for an operation with the following search parameters:
- patient = eAB3mDIBBcyUKviyzrxsnAw3
- code = 4548-4

you should use then the `Search` operation. So not the `Read` operation, but the following:

```c#
  var srchParams = new SearchParams()
                .Add("patient", "eAB3mDIBBcyUKviyzrxsnAw3")
                .Add("code", "4548-4");
  var result = client.Search<Observation>(srchParams);
```
You can also have a look at our documentation site: https://docs.fire.ly/fhirnetapi/client/search.html.

The `Read` method is for searching a resource when you have already the `id`.

**Comment by brianpos** [comment] 2020-10-29 23:00
To help debug things like this it's often useful to use the OnAfterEvent, and OnBeforeEvent and look at the raw request/response to see what it was trying to call. Then you can likely see the malformed URL it's trying to use.

**Comment by marcovisserFurore** [comment] 2020-11-03 12:30
The issue is answered, so closing this issue.

**Closed by marcovisserFurore** 2020-11-03 12:30 UTC
Labels: support

**Comment by tscrip** [comment] 2020-11-03 17:13
Thanks guys. I figured this was probably a use case problem. @brianpos Thanks for that tip. That helps SO MUCH with the troubleshooting side of things.
