### ISSUE TITLE
snapshot generator does not generate base.min/max in some cases

### ISSUE THREAD

**Issue by furoreSebastiaan** [FirelyTeam/fhir-net-api#1153] opened 2019-10-18 09:04 UTC
reproduction path:

1. go to https://simplifier.net/grunndata-r4/person
2. validate it --> OK
3. Download the snapshot.
4. validate the snapshot --> NOT OK, errors in required .base.min and .base.max. They're missing in one element

```
    <element id="Person.meta.security:addressConfidentiality.extension">
      <path value="Person.meta.security.extension" />
      <slicing>
        <discriminator>
          <type value="value" />
          <path value="url" />
        </discriminator>
        <rules value="open" />
      </slicing>
      <base>
        <path value="Person.meta.security.extension" />
      </base>
    </element>

```

**Comment by marcovisserFurore** [comment] 2019-10-21 12:44
@wmrutten: can you investigate this?

**Comment by wardweistra** [comment] 2019-11-06 14:30
Could the warning message on this Example be related: https://simplifier.net/nictizstu3-zib2017/patient-example-duplicate-7/$validate (@marcovisserFurore and I thought it could be):
`BusinessRule: Element definition does not specify a 'min' value, which is required. Cardinality has not been validated. Patient.contact[0]`

While https://simplifier.net/NictizSTU3-Zib2017/nl-core-patient/, to which the example conforms, does have a min/max defined for Patient.contact when downloading the snapshot.

**Comment by MatthijsvdWielen** [comment] 2020-02-25 15:11
The path in the initial message is not reproducible  anymore. The linked profile has been altered in the mean time. The error occurred with version 7 of the profile. 

The error is: 
"Invariant : Instance failed constraint sdf-3 "Each element definition in a snapshot must have a formal definition and cardinalities"
Diagnostics: element.all(definition.exists() and min.exists() and max.exists())
StructureDefinition.snapshot[0] "

I've added the txt file for the version that produced the error. 
[PersonV7Grunn.txt](https://github.com/FirelyTeam/fhir-net-api/files/4250670/PersonV7Grunn.txt)

**Comment by MatthijsvdWielen** [comment] 2020-02-26 07:56
@marcovisserFurore Could you please close this issue. It's a duplicate of #1227 .

**Comment by marcovisserFurore** [comment] 2020-02-27 09:15
Closing issue..

**Closed by marcovisserFurore** 2020-02-27 09:15 UTC
Labels: support
