### ISSUE TITLE
When element has multiple discriminators including a pattern validator fails on elements without pattern

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/fhir-net-api#1246] opened 2020-02-05 03:35 UTC
See for example: https://simplifier.net/agencystu3/practitioner-example-duplicate-2/$validate
(Instance of profile: https://simplifier.net/agencystu3/aubasepractitioner)

In the profile identifier is sliced on both pattern and value. Some identifier slices have a pattern, some don't. On validating the instance validator seems to complains that not all slices have a pattern:
`Exception : Internal logic failure: The pattern discriminator should have a 'pattern[x]' element set on 'http://hl7.org.au/fhir/StructureDefinition/au-practitioner#Practitioner.identifier.type'.`

Behavior should be that validator should try to slice on both pattern and value, is what I understand from Alexander. This is an issue that appeared for one of our customers.

**Comment by wardweistra** [comment] 2020-02-13 16:19
Another customer mentioned they encountered this issue

**Comment by mmsmits** [comment] 2020-03-23 09:48
I believe it relates to this issue
https://jira.hl7.org/browse/FHIR-25206?filter=-2

**Comment by ewoutkramer** [comment] 2020-04-02 10:29
It has not such much to do with multiple discriminators, but rather with the fact that the author of the profile has a usecase where he wishes to slice *the same element* on a pattern in some slices, on a binding in others, and sometimes on both. However, for each slicing discriminator you have to indicate the type, which is an *exclusive* choice between pattern (for patterns) or value (for bindings or fixed values), so there is no way to express that.

The profile as mentioned above clearly shows this problem: 
* There is a discriminator on `Practitioner.identifier.type` (also on `.system`, but that's irrelevant here)
* The discriminator is of type `pattern` - so the validator expects `pattern[x]` to be set on the subsequent slice definitions (called hpii, medicarePrescriberNumber, careAgency.....).
* The slice `careAgencyEmployeeIdentifier` has no pattern set in its slice constraints - it just has a binding. 
* The validator sees a discriminator of type pattern, but no pattern set for one of the slices and complains about this.

The solution chosen by the FHIR-I WG is to avoid this binary choice by collapsing `value` and `pattern` into one. This means that setting a discriminator to either type will use fixed[x] AND pattern[x] AND binding to discriminate a slice. There is no requirement that all three are present, so the author can pick any combination.

Implementing this in the R3 and R4 validators may cause backwards-compatibility issues: if a discriminator is of type pattern and there are slices with a bindings set as well, currently an instance would be determined to be in a certain slice based on that pattern and would then fail the binding constraint for that slice, but it still considered to be in that slice. In the new situation this instance would not be considered as matching the slice, so would end up in the open part (for open slices), or the @default slice, or (for closed slices) the validator would announce it does not fit in any slice. This is clearly non-backwards compatible behaviour. I have reported this to HL7.

For now, I _will_ implement this in R3 and R4 since the usecase is clear and necessary - but it will prevent people from having the possibility to discriminate on a pattern and then have a simple constraint on the binding.

**Comment by ewoutkramer** [comment] 2020-04-02 10:36
Another issue is that the validator's message should not have said "Internal error" and should have indicated the slice at fault here. I will try to fix that too.

**Comment by ewoutkramer** [comment] 2020-04-02 12:14
Ardon reported that this is a duplicate of #1185, which is correct.

**Closed** 2020-04-16 09:47 UTC
Labels: enhancement
