### ISSUE TITLE
CCDA on FHIR models need to read in XML element content, not XML value attributes

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1209] opened 2020-01-08 15:07 UTC
Other models represented by a FHIR StructureDefinition may not always adhere to the XML representation of FHIR. Most notably some models will have content as XML element content (<tag>content</tag>) and not within "value" attributes.

**Comment by ewoutkramer** [comment] 2020-03-02 10:11
Duplicate of #1221?

**Closed** 2020-03-04 12:22 UTC
Labels: ccda
