### ISSUE TITLE
[Validator] does not validate extension context

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#937] opened 2019-04-10 14:51 UTC
Validation of the zib-medicationuse profile gives a success while it has an extension which is not valid given the extension context.  

Profile:
`   
<element id="MedicationStatement.extension:practitionerRole">
            <path value="MedicationStatement.extension" />
            <sliceName value="practitionerRole" />
            <max value="1" />
            <type>
                <code value="Extension" />
                <profile value="http://nictiz.nl/fhir/StructureDefinition/practitionerrole-reference" />
            </type>
</element>
`

Extension (practitionerrole-reference) has:

`    <contextType value="datatype" />
    <context value="Reference" />
    <type value="Extension" />`

Profile and extension: see the .zip file
The entire project and package: https://simplifier.net/nictizstu3-zib2017 
[Validator extension.zip](https://github.com/FirelyTeam/fhir-net-api/files/3064391/Validator.extension.zip)

Perhaps a duplicate of: [Validator] Enforce StructureDefinition.context/contextType #463

**Comment by ewoutkramer** [comment] 2019-04-10 16:01
Nope, it does not.  Indeed a duplicate of #463 ;-)

**Closed** 2019-04-15 07:53 UTC
Labels: duplicate
