### ISSUE TITLE
Fix SimpleQuantity datatype definition, remove invalid sliceName on root element

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#618] opened 2018-06-11 12:05 UTC
In STU3, the SimpleQuantity datatype definition in profiles-types.xml specifies an invalid non-empty sliceName on the root element

```
          <element id="Quantity:simplequantity">
            <path value="Quantity"/>
            <sliceName value="SimpleQuantity"/>
```
This is illegal and causes the snapshot generator to always emit an error for each profile that references SimpleQuantity datatype, e.g. when expanding an Observation profile. Although technically, the error message is correct and indicates a bug in the spec, this is not very helpful and confusing to end users.

Propose to simply hack the included profiles-types.xml in specification.zip and remove the illegal sliceName property value from the SimpleQuantity datatype profile.

**Comment by ewoutkramer** [comment] 2018-06-12 07:44
Agree, we'd need to check for regression bugs though, who knows what is dependent on this element?  Maybe we can check the source code to see if anything is referencing this element in addition to Michel's snapshot generator code....

**Comment by wmrutten** [comment] 2018-06-12 08:54
In the latest Forge release (19.1), I've added some custom initialization logic to explicitly strip the illegal slicename from the root element of the SimpleQuantity core datatype definition. This permanently suppresses the error message and also prevents user profiles from inheriting the illegal sliceName.

Therefore Forge does not rely on the API to fix this. However if we decide to, then I can remove the custom logic in Forge.

**Comment by ArdonToonstra** [comment] 2020-03-31 12:10
Does this still occur?  Perhaps this issue can be closed @marcovisserFurore?

**Comment by mmsmits** [comment] 2020-06-18 11:56
This illegal sliceName doesn't occur anymore in version 3.0.2, so we can close this issue

**Comment by mmsmits** [comment] 2020-07-09 09:41
Turns out this still occurs, we will suppress this warning, in a future hotfix

**Closed** 2020-07-13 16:51 UTC
Labels: bug
