### ISSUE TITLE
Unexpected reference errors about type

### ISSUE THREAD

**Issue by ahenket** [FirelyTeam/fhir-net-api#1027] opened 2019-07-03 14:08 UTC
Loading attached Bundle into https://simplifier.net/validate which I assume represents the latest version of the .Net validator gives back some informational messages I can't explain.

```Invalid : The declared type of the element (Group) is incompatible with that of the instance ('Patient')```

At first glance you'd think it is about type slicing which is also reported, but the element it (presumably) concerns is not sliced at all. See Procedure.subject in [HCIM Procedure](https://simplifier.net/nictizstu3-zib2017/zib-procedure)

So in short it seems the informational messages are about the validator discovering that the reference resolves to a Patient. The element is (Group | Patient) so it first determines that Patient != Group, reports that and then finds out that Patient == Patient, so all is well. 

Could the informational message be skipped here too? What I'd like to see is either nothing, or:

```Invalid: The instance type of the reference ('Patient') does not match any of the stated types for the element (Group | Patient)```

By the way this also raises the question: the profile says it shall not be just any Patient, but specifically profiled to nl-core-patient. So: is "Patient" valid, or is "nl-core-patient"?

![Schermafbeelding 2019-07-03 om 15 58 14](https://user-images.githubusercontent.com/5390573/60597768-c87b4100-9dab-11e9-8960-18b603df0165.png)

[Bundle.txt](https://github.com/FirelyTeam/fhir-net-api/files/3355300/Bundle.txt)

**Comment by ewoutkramer** [comment] 2019-07-03 14:44
Probably a duplicate of #736.  Good news: in that case this has been fixed in the upcoming release.

**Comment by ewoutkramer** [comment] 2019-07-03 14:49
To answer your question: it will consider Patient to be valid, but when the validator is then validating the references, it will validate the referenced resource against that profile.  That's done during a different validation phase, but it will be done.

**Closed** 2019-07-10 13:00 UTC
